# Feature Engineering - Technical Indicators

## Setup

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from pathlib import Path

# Configurable parts
SYMBOL = "USDJPY"
SAMPLE_TYPE = "time"
MINUTES = 1

START_DATE = "20240101"
END_DATE = "20241231"

# Build base name
RESAMPLED_NAME = f"{SYMBOL}-{MINUTES}m-{START_DATE}-{END_DATE}"

# Base directories
BASE_DIR = Path("../data")
RESAMPLED_DIR = BASE_DIR / "resampled"
PROCESSED_DIR = BASE_DIR / "processed"
EVENTS_DIR = BASE_DIR / "events"

# Final paths
RESAMPLED_FILE_PATH = RESAMPLED_DIR / f"{RESAMPLED_NAME}.pkl"
PROCESSED_FILE_PATH = PROCESSED_DIR / f"{RESAMPLED_NAME}-TA.pkl"

## Load Data

In [3]:
%%time
df = pd.read_pickle(RESAMPLED_FILE_PATH)

CPU times: user 622 μs, sys: 3.87 ms, total: 4.49 ms
Wall time: 7.18 ms

In [4]:
df.shape

(372063, 7)

In [5]:
df.head()

,open,high,low,close,volume,spread,tick
timestamp,,,,,,,
2024-01-01 22:00:00,140.8730,140.8730,140.8695,140.8720,7.8,0.0468,5
2024-01-01 22:01:00,140.8720,140.8720,140.8720,140.8720,1.4,0.0400,1
2024-01-01 22:02:00,140.8705,140.8705,140.8705,140.8705,1.4,0.0410,1
2024-01-01 22:03:00,140.8655,140.8655,140.8655,140.8655,1.4,0.0510,1
2024-01-01 22:05:00,140.8660,140.8660,140.8660,140.8660,2.1,0.0500,1

In [6]:
df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
df = df.set_index('timestamp')

KeyError: 'timestamp'

## Technical Indicators

In [ ]:
import pandas_ta as ta

In [ ]:
print(df.ta.indicators())

SMA

In [ ]:
df.ta.sma(length=5, append=True)
df.ta.sma(length=15, append=True)
df.ta.sma(length=30, append=True)
df.ta.sma(length=60, append=True)
df[100:105]

#### EMA

In [ ]:
df.ta.ema(length=5, append=True)
df.ta.ema(length=15, append=True)
df.ta.ema(length=30, append=True)
df.ta.ema(length=60, append=True)
df[100:105]

MACD

In [ ]:
df.ta.macd(append=True)
df[100:105]

RSI

In [ ]:
df.ta.rsi(length=5, append=True)
df.ta.rsi(length=14, append=True)
df.ta.rsi(length=20, append=True)
df[100:105]

ADX

In [ ]:
df.ta.adx(length=5, append=True)
df.ta.adx(length=15, append=True)
df.ta.adx(length=30, append=True)
df.ta.adx(length=60, append=True)
df[100:105]

BBands

In [14]:
df.ta.bbands(length=15, append=True)
df[100:105]

,open,high,low,close,volume,spread,SMA_5,SMA_15,SMA_30,SMA_60,...,DMN_30,ADX_60,ADXR_60_2,DMP_60,DMN_60,BBL_15_2.0_2.0,BBM_15_2.0_2.0,BBU_15_2.0_2.0,BBB_15_2.0_2.0,BBP_15_2.0_2.0
timestamp,,,,,,,,,,,,,,,,,,,,,
2024-01-01 23:44:00,1.103685,1.103720,1.103685,1.103690,7.380000e+10,0.000032,1.103726,1.103741,1.103757,1.104001,...,0.000537,NaN,NaN,0.000465,0.000959,1.103642,1.103741,1.103840,0.018026,0.243664
2024-01-01 23:45:00,1.103685,1.103750,1.103655,1.103695,1.864700e+11,0.000037,1.103707,1.103736,1.103753,1.103990,...,0.000549,NaN,NaN,0.000457,0.000973,1.103635,1.103736,1.103837,0.018243,0.296380
2024-01-01 23:46:00,1.103700,1.103700,1.103685,1.103690,1.107000e+11,0.000038,1.103702,1.103730,1.103750,1.103979,...,0.000531,NaN,NaN,0.000449,0.000957,1.103630,1.103730,1.103829,0.018029,0.300663
2024-01-01 23:47:00,1.103685,1.103730,1.103685,1.103700,1.257800e+11,0.000035,1.103695,1.103729,1.103747,1.103968,...,0.000513,NaN,NaN,0.000472,0.000941,1.103628,1.103729,1.103829,0.018186,0.357186
2024-01-01 23:48:00,1.103710,1.103735,1.103645,1.103645,7.650000e+10,0.000028,1.103684,1.103728,1.103744,1.103956,...,0.000536,NaN,NaN,0.000464,0.000965,1.103627,1.103728,1.103830,0.018380,0.089225

ATR

In [15]:
df.ta.atr(length=5, append=True)
df.ta.atr(length=10, append=True)
df.ta.atr(length=15, append=True)
df.ta.atr(length=20, append=True)
df[100:105]

,open,high,low,close,volume,spread,SMA_5,SMA_15,SMA_30,SMA_60,...,DMN_60,BBL_15_2.0_2.0,BBM_15_2.0_2.0,BBU_15_2.0_2.0,BBB_15_2.0_2.0,BBP_15_2.0_2.0,ATRr_5,ATRr_10,ATRr_15,ATRr_20
timestamp,,,,,,,,,,,,,,,,,,,,,
2024-01-01 23:44:00,1.103685,1.103720,1.103685,1.103690,7.380000e+10,0.000032,1.103726,1.103741,1.103757,1.104001,...,0.000959,1.103642,1.103741,1.103840,0.018026,0.243664,0.000056,0.000057,0.000057,0.000056
2024-01-01 23:45:00,1.103685,1.103750,1.103655,1.103695,1.864700e+11,0.000037,1.103707,1.103736,1.103753,1.103990,...,0.000973,1.103635,1.103736,1.103837,0.018243,0.296380,0.000064,0.000061,0.000059,0.000058
2024-01-01 23:46:00,1.103700,1.103700,1.103685,1.103690,1.107000e+11,0.000038,1.103702,1.103730,1.103750,1.103979,...,0.000957,1.103630,1.103730,1.103829,0.018029,0.300663,0.000054,0.000056,0.000056,0.000055
2024-01-01 23:47:00,1.103685,1.103730,1.103685,1.103700,1.257800e+11,0.000035,1.103695,1.103729,1.103747,1.103968,...,0.000941,1.103628,1.103729,1.103829,0.018186,0.357186,0.000052,0.000055,0.000056,0.000055
2024-01-01 23:48:00,1.103710,1.103735,1.103645,1.103645,7.650000e+10,0.000028,1.103684,1.103728,1.103744,1.103956,...,0.000965,1.103627,1.103728,1.103830,0.018380,0.089225,0.000060,0.000059,0.000058,0.000057

Bolliger Bands

In [16]:
df.ta.bbands(length=5, append=True)
df.ta.bbands(length=14, append=True)
df[100:105]

,open,high,low,close,volume,spread,SMA_5,SMA_15,SMA_30,SMA_60,...,BBL_5_2.0_2.0,BBM_5_2.0_2.0,BBU_5_2.0_2.0,BBB_5_2.0_2.0,BBP_5_2.0_2.0,BBL_14_2.0_2.0,BBM_14_2.0_2.0,BBU_14_2.0_2.0,BBB_14_2.0_2.0,BBP_14_2.0_2.0
timestamp,,,,,,,,,,,,,,,,,,,,,
2024-01-01 23:44:00,1.103685,1.103720,1.103685,1.103690,7.380000e+10,0.000032,1.103726,1.103741,1.103757,1.104001,...,1.103655,1.103726,1.103797,0.012834,0.245848,1.103637,1.103739,1.103841,0.018431,0.259476
2024-01-01 23:45:00,1.103685,1.103750,1.103655,1.103695,1.864700e+11,0.000037,1.103707,1.103736,1.103753,1.103990,...,1.103674,1.103707,1.103740,0.005911,0.316058,1.103632,1.103732,1.103833,0.018233,0.313661
2024-01-01 23:46:00,1.103700,1.103700,1.103685,1.103690,1.107000e+11,0.000038,1.103702,1.103730,1.103750,1.103979,...,1.103668,1.103702,1.103736,0.006129,0.322606,1.103628,1.103731,1.103833,0.018604,0.301720
2024-01-01 23:47:00,1.103685,1.103730,1.103685,1.103700,1.257800e+11,0.000035,1.103695,1.103729,1.103747,1.103968,...,1.103686,1.103695,1.103704,0.001621,0.779507,1.103640,1.103734,1.103829,0.017093,0.318265
2024-01-01 23:48:00,1.103710,1.103735,1.103645,1.103645,7.650000e+10,0.000028,1.103684,1.103728,1.103744,1.103956,...,1.103644,1.103684,1.103724,0.007194,0.008802,1.103631,1.103732,1.103833,0.018258,0.067582

### Remove NaN Values

In [17]:
df.dropna(inplace=True)

### Save to Disk

In [18]:
df.to_pickle(PROCESSED_FILE_PATH)